def throw_an_error():
    raise RuntimeError('An error was raised on purpose')